# Generated by Django 2.2 on 2018-09-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectioEx', '0002_auto_20180926_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='upload_date',
            field=models.DateTimeField(null=True, verbose_name='uploade date'),
        ),
    ]
