# Generated by Django 2.2 on 2018-09-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectioEx', '0003_badge_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(null=True, upload_to='badges'),
        ),
    ]
